// ─────────────────────────────────────────────
// Portfolio Data: Developer profile & content
// ─────────────────────────────────────────────

export const DEVELOPER = {
  name: 'Nithin Das',
  title: 'Software Developer',
  tagline: 'ARCHITECT THE FUTURE',
  subTagline: 'CRAFT THE CODE',
  bio: `Full-stack software developer passionate about building high-performance, scalable digital experiences. 
  I blend clean architecture with creative engineering to turn complex ideas into elegant software.`,
  shortBio: 'Building scalable systems & seamless digital experiences.',
  location: 'India',
  email: 'nithindaskavungal@gmail.com',
  phone: '8921642524',
  whatsapp: 'https://wa.me/918921642524',
  linkedin: 'https://www.linkedin.com/in/nithin-das-9b932123a/',
  github: 'https://github.com/nithindas-k',
  available: true,
  avatar: '/assets/character.jpg',
  yearsExp: 3,
  projectsDone: 20,
  clients: 10,
};

export const SKILLS = {
  frontend: [
    'React',
    'TypeScript',
    'Redux Toolkit',
    'Zustand',
    'Tailwind CSS',
    'Vite',
    'Framer Motion',
    'GSAP',
    'Three.js',
    'Radix UI / shadcn-ui',
    'HTML5',
    'CSS3',
  ],
  backend: [
    'Node.js',
    'Express.js',
    'MongoDB',
    'Mongoose',
    'JWT Auth',
    'Passport.js (Google OAuth)',
    'Socket.io',
    'PostgreSQL',
    'Redis',
    'Firebase',
  ],
  tools: [
    'Git & GitHub',
    'AWS',
    'Vercel',
    'Render',
    'Cloudinary',
    'Razorpay',
    'Groq AI / LLM APIs',
    'Data Structures & Algorithms (DSA)',
  ],
};

export const TECH_TAGS = [
  'React',
  'TypeScript',
  'JavaScript',
  'Node.js',
  'Express.js',
  'MongoDB',
  'PostgreSQL',
  'Redis',
  'Firebase',
  'Java',
  'C++',
  'C',
  'Tailwind CSS',
  'Framer Motion',
  'GSAP',
  'Three.js',
  'Socket.io',
  'JWT',
  'Google OAuth',
  'Cloudinary',
  'Razorpay',
  'Groq AI',
  'AWS',
  'Vercel',
  'Render',
  'Git',
  'GitHub',
];

export const PROJECTS = [
  {
    id: 1,
    title: 'TakeCare',
    category: 'Fullstack',
    description: 'Full-stack healthcare platform connecting patients and doctors — real-time appointment booking, doctor dashboards, secure payments via Razorpay, and Google OAuth login, built on the MERN stack with TypeScript.',
    tech: ['React', 'Node.js', 'MongoDB', 'Socket.io', 'TypeScript'],
    liveUrl: 'https://takecare.nithin.site',
    githubUrl: 'https://github.com/nithindas-k/Takecare',
    featured: true,
    gradient: 'linear-gradient(135deg, #00A1B0 0%, #004D54 100%)',
  },
  {
    id: 2,
    title: 'Docs',
    category: 'Fullstack',
    description: 'Secure personal and family document vault with an immersive 3D interface — encrypted Cloudinary storage, Google OAuth sign-in, global document search, and member-based family archiving, built with React and Three.js.',
    tech: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Three.js'],
    liveUrl: 'https://docs-nithin.vercel.app',
    githubUrl: 'https://github.com/nithindas-k/Docs',
    featured: false,
    gradient: 'linear-gradient(135deg, #4A4E6A 0%, #2A2D3E 100%)',
  },
  {
    id: 3,
    title: 'Stockify',
    category: 'Fullstack',
    description: 'Professional inventory management system with a built-in POS — real-time stock tracking, low-stock alerts, sales reporting with PDF/Excel export, and automated email delivery of reports, built on the MERN stack.',
    tech: ['React', 'Node.js', 'MongoDB', 'TypeScript', 'JWT'],
    liveUrl: 'https://stockify-wine.vercel.app',
    previewUrl: 'https://stockify-nithin.vercel.app/login',
    githubUrl: 'https://github.com/nithindas-k/Stockify-',
    featured: true,
    gradient: 'linear-gradient(135deg, #0f3460 0%, #16213e 100%)',
  },
  {
    id: 4,
    title: 'LazyDraft',
    category: 'Fullstack',
    description: 'AI-powered email drafting and automation platform integrated with Gmail — generates context-aware emails with adjustable tone and length, handles scheduled and recurring sends, and auto-replies using Groq AI, all through a live analytics dashboard.',
    tech: ['React', 'TypeScript', 'Node.js', 'MongoDB', 'Groq AI'],
    liveUrl: 'https://lazydraft.nithin.site',
    githubUrl: 'https://github.com/nithindas-k/LazyDraft',
    featured: true,
    gradient: 'linear-gradient(135deg, #2D3140 0%, #1E2028 100%)',
  },
  {
    id: 5,
    title: 'LapEdge',
    category: 'Fullstack',
    description: 'Full-stack e-commerce platform built with Node.js, Express, and EJS — includes user authentication, product catalog, cart, and order management with a server-rendered MVC architecture.',
    tech: ['Node.js', 'Express', 'MongoDB', 'EJS'],
    liveUrl: '',
    previewUrl: 'https://lapedge.onrender.com/',
    githubUrl: 'https://github.com/nithindas-k/lapedge',
    featured: false,
    gradient: 'linear-gradient(135deg, #3d5a3e 0%, #1e2d1e 100%)',
  },
  {
    id: 6,
    title: 'SnapURL',
    category: 'Backend',
    description: 'High-performance URL shortening and analytics platform built with Node.js, Express, and MongoDB — features instant link redirection, custom aliases, and click tracking metrics.',
    tech: ['Node.js', 'Express', 'MongoDB'],
    liveUrl: 'https://snap-url-nithin.vercel.app',
    githubUrl: 'https://github.com/nithindas-k/snapurl',
    featured: false,
    gradient: 'linear-gradient(135deg, #657152 0%, #4A543C 100%)',
  },
];

export const EXPERIENCE = [
  {
    id: 1,
    role: 'Full Stack Development Student',
    company: 'Brototype',
    period: '2024 – Present',
    type: 'Training Program',
    description:
      'Completing an intensive, project-based full-stack development program at Brototype — building production-grade MERN applications (TakeCare, LazyDraft, Stockify) from scratch through self-research-driven, mentor-guided learning.',
    highlights: [
      'Shipped 6+ full-stack projects independently, from architecture to deployment',
      'Built and deployed live applications using React, Node.js, MongoDB, and TypeScript',
      'Applied DSA and problem-solving skills across 227+ LeetCode problems solved',
    ],
  },
];

export const CATEGORIES = ['All', 'Fullstack', 'Frontend', 'Backend'];
